// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/assistant/embedded/v1alpha2/embedded_assistant.proto

package com.google.assistant.embedded.v1alpha2;

/**
 * <pre>
 * The top-level message received by the client. A series of one or more
 * `AssistResponse` messages are streamed back to the client.
 * </pre>
 *
 * Protobuf type {@code google.assistant.embedded.v1alpha2.AssistResponse}
 */
public  final class AssistResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.assistant.embedded.v1alpha2.AssistResponse)
    AssistResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AssistResponse.newBuilder() to construct.
  private AssistResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AssistResponse() {
    eventType_ = 0;
    speechResults_ = java.util.Collections.emptyList();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AssistResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            eventType_ = rawValue;
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              speechResults_ = new java.util.ArrayList<SpeechRecognitionResult>();
              mutable_bitField0_ |= 0x00000008;
            }
            speechResults_.add(
                input.readMessage(SpeechRecognitionResult.parser(), extensionRegistry));
            break;
          }
          case 26: {
            AudioOut.Builder subBuilder = null;
            if (audioOut_ != null) {
              subBuilder = audioOut_.toBuilder();
            }
            audioOut_ = input.readMessage(AudioOut.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(audioOut_);
              audioOut_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            DialogStateOut.Builder subBuilder = null;
            if (dialogStateOut_ != null) {
              subBuilder = dialogStateOut_.toBuilder();
            }
            dialogStateOut_ = input.readMessage(DialogStateOut.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(dialogStateOut_);
              dialogStateOut_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            DeviceAction.Builder subBuilder = null;
            if (deviceAction_ != null) {
              subBuilder = deviceAction_.toBuilder();
            }
            deviceAction_ = input.readMessage(DeviceAction.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(deviceAction_);
              deviceAction_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        speechResults_ = java.util.Collections.unmodifiableList(speechResults_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return AssistantProto.internal_static_google_assistant_embedded_v1alpha2_AssistResponse_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return AssistantProto.internal_static_google_assistant_embedded_v1alpha2_AssistResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            AssistResponse.class, Builder.class);
  }

  /**
   * <pre>
   * Indicates the type of event.
   * </pre>
   *
   * Protobuf enum {@code google.assistant.embedded.v1alpha2.AssistResponse.EventType}
   */
  public enum EventType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * No event specified.
     * </pre>
     *
     * <code>EVENT_TYPE_UNSPECIFIED = 0;</code>
     */
    EVENT_TYPE_UNSPECIFIED(0),
    /**
     * <pre>
     * This event indicates that the server has detected the end of the user's
     * speech utterance and expects no additional speech. Therefore, the server
     * will not process additional audio (although it may subsequently return
     * additional results). The client should stop sending additional audio
     * data, half-close the gRPC connection, and wait for any additional results
     * until the server closes the gRPC connection.
     * </pre>
     *
     * <code>END_OF_UTTERANCE = 1;</code>
     */
    END_OF_UTTERANCE(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * No event specified.
     * </pre>
     *
     * <code>EVENT_TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int EVENT_TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <pre>
     * This event indicates that the server has detected the end of the user's
     * speech utterance and expects no additional speech. Therefore, the server
     * will not process additional audio (although it may subsequently return
     * additional results). The client should stop sending additional audio
     * data, half-close the gRPC connection, and wait for any additional results
     * until the server closes the gRPC connection.
     * </pre>
     *
     * <code>END_OF_UTTERANCE = 1;</code>
     */
    public static final int END_OF_UTTERANCE_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static EventType valueOf(int value) {
      return forNumber(value);
    }

    public static EventType forNumber(int value) {
      switch (value) {
        case 0: return EVENT_TYPE_UNSPECIFIED;
        case 1: return END_OF_UTTERANCE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EventType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EventType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EventType>() {
            public EventType findValueByNumber(int number) {
              return EventType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AssistResponse.getDescriptor().getEnumTypes().get(0);
    }

    private static final EventType[] VALUES = values();

    public static EventType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EventType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:google.assistant.embedded.v1alpha2.AssistResponse.EventType)
  }

  private int bitField0_;
  public static final int EVENT_TYPE_FIELD_NUMBER = 1;
  private int eventType_;
  /**
   * <pre>
   * *Output-only* Indicates the type of event.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.AssistResponse.EventType event_type = 1;</code>
   */
  public int getEventTypeValue() {
    return eventType_;
  }
  /**
   * <pre>
   * *Output-only* Indicates the type of event.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.AssistResponse.EventType event_type = 1;</code>
   */
  public EventType getEventType() {
    EventType result = EventType.valueOf(eventType_);
    return result == null ? EventType.UNRECOGNIZED : result;
  }

  public static final int AUDIO_OUT_FIELD_NUMBER = 3;
  private AudioOut audioOut_;
  /**
   * <pre>
   * *Output-only* The audio containing the Assistant's response to the query.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.AudioOut audio_out = 3;</code>
   */
  public boolean hasAudioOut() {
    return audioOut_ != null;
  }
  /**
   * <pre>
   * *Output-only* The audio containing the Assistant's response to the query.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.AudioOut audio_out = 3;</code>
   */
  public AudioOut getAudioOut() {
    return audioOut_ == null ? AudioOut.getDefaultInstance() : audioOut_;
  }
  /**
   * <pre>
   * *Output-only* The audio containing the Assistant's response to the query.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.AudioOut audio_out = 3;</code>
   */
  public AudioOutOrBuilder getAudioOutOrBuilder() {
    return getAudioOut();
  }

  public static final int DEVICE_ACTION_FIELD_NUMBER = 6;
  private DeviceAction deviceAction_;
  /**
   * <pre>
   * *Output-only* Contains the action triggered by the query with the
   * appropriate payloads and semantic parsing.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DeviceAction device_action = 6;</code>
   */
  public boolean hasDeviceAction() {
    return deviceAction_ != null;
  }
  /**
   * <pre>
   * *Output-only* Contains the action triggered by the query with the
   * appropriate payloads and semantic parsing.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DeviceAction device_action = 6;</code>
   */
  public DeviceAction getDeviceAction() {
    return deviceAction_ == null ? DeviceAction.getDefaultInstance() : deviceAction_;
  }
  /**
   * <pre>
   * *Output-only* Contains the action triggered by the query with the
   * appropriate payloads and semantic parsing.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DeviceAction device_action = 6;</code>
   */
  public DeviceActionOrBuilder getDeviceActionOrBuilder() {
    return getDeviceAction();
  }

  public static final int SPEECH_RESULTS_FIELD_NUMBER = 2;
  private java.util.List<SpeechRecognitionResult> speechResults_;
  /**
   * <pre>
   * *Output-only* This repeated list contains zero or more speech recognition
   * results that correspond to consecutive portions of the audio currently
   * being processed, starting with the portion corresponding to the earliest
   * audio (and most stable portion) to the portion corresponding to the most
   * recent audio. The strings can be concatenated to view the full
   * in-progress response. When the speech recognition completes, this list
   * will contain one item with `stability` of `1.0`.
   * </pre>
   *
   * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
   */
  public java.util.List<SpeechRecognitionResult> getSpeechResultsList() {
    return speechResults_;
  }
  /**
   * <pre>
   * *Output-only* This repeated list contains zero or more speech recognition
   * results that correspond to consecutive portions of the audio currently
   * being processed, starting with the portion corresponding to the earliest
   * audio (and most stable portion) to the portion corresponding to the most
   * recent audio. The strings can be concatenated to view the full
   * in-progress response. When the speech recognition completes, this list
   * will contain one item with `stability` of `1.0`.
   * </pre>
   *
   * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
   */
  public java.util.List<? extends SpeechRecognitionResultOrBuilder>
      getSpeechResultsOrBuilderList() {
    return speechResults_;
  }
  /**
   * <pre>
   * *Output-only* This repeated list contains zero or more speech recognition
   * results that correspond to consecutive portions of the audio currently
   * being processed, starting with the portion corresponding to the earliest
   * audio (and most stable portion) to the portion corresponding to the most
   * recent audio. The strings can be concatenated to view the full
   * in-progress response. When the speech recognition completes, this list
   * will contain one item with `stability` of `1.0`.
   * </pre>
   *
   * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
   */
  public int getSpeechResultsCount() {
    return speechResults_.size();
  }
  /**
   * <pre>
   * *Output-only* This repeated list contains zero or more speech recognition
   * results that correspond to consecutive portions of the audio currently
   * being processed, starting with the portion corresponding to the earliest
   * audio (and most stable portion) to the portion corresponding to the most
   * recent audio. The strings can be concatenated to view the full
   * in-progress response. When the speech recognition completes, this list
   * will contain one item with `stability` of `1.0`.
   * </pre>
   *
   * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
   */
  public SpeechRecognitionResult getSpeechResults(int index) {
    return speechResults_.get(index);
  }
  /**
   * <pre>
   * *Output-only* This repeated list contains zero or more speech recognition
   * results that correspond to consecutive portions of the audio currently
   * being processed, starting with the portion corresponding to the earliest
   * audio (and most stable portion) to the portion corresponding to the most
   * recent audio. The strings can be concatenated to view the full
   * in-progress response. When the speech recognition completes, this list
   * will contain one item with `stability` of `1.0`.
   * </pre>
   *
   * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
   */
  public SpeechRecognitionResultOrBuilder getSpeechResultsOrBuilder(
      int index) {
    return speechResults_.get(index);
  }

  public static final int DIALOG_STATE_OUT_FIELD_NUMBER = 5;
  private DialogStateOut dialogStateOut_;
  /**
   * <pre>
   * *Output-only* Contains output related to the user's query.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DialogStateOut dialog_state_out = 5;</code>
   */
  public boolean hasDialogStateOut() {
    return dialogStateOut_ != null;
  }
  /**
   * <pre>
   * *Output-only* Contains output related to the user's query.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DialogStateOut dialog_state_out = 5;</code>
   */
  public DialogStateOut getDialogStateOut() {
    return dialogStateOut_ == null ? DialogStateOut.getDefaultInstance() : dialogStateOut_;
  }
  /**
   * <pre>
   * *Output-only* Contains output related to the user's query.
   * </pre>
   *
   * <code>.google.assistant.embedded.v1alpha2.DialogStateOut dialog_state_out = 5;</code>
   */
  public DialogStateOutOrBuilder getDialogStateOutOrBuilder() {
    return getDialogStateOut();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (eventType_ != EventType.EVENT_TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, eventType_);
    }
    for (int i = 0; i < speechResults_.size(); i++) {
      output.writeMessage(2, speechResults_.get(i));
    }
    if (audioOut_ != null) {
      output.writeMessage(3, getAudioOut());
    }
    if (dialogStateOut_ != null) {
      output.writeMessage(5, getDialogStateOut());
    }
    if (deviceAction_ != null) {
      output.writeMessage(6, getDeviceAction());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (eventType_ != EventType.EVENT_TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, eventType_);
    }
    for (int i = 0; i < speechResults_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, speechResults_.get(i));
    }
    if (audioOut_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAudioOut());
    }
    if (dialogStateOut_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getDialogStateOut());
    }
    if (deviceAction_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getDeviceAction());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof AssistResponse)) {
      return super.equals(obj);
    }
    AssistResponse other = (AssistResponse) obj;

    boolean result = true;
    result = result && eventType_ == other.eventType_;
    result = result && (hasAudioOut() == other.hasAudioOut());
    if (hasAudioOut()) {
      result = result && getAudioOut()
          .equals(other.getAudioOut());
    }
    result = result && (hasDeviceAction() == other.hasDeviceAction());
    if (hasDeviceAction()) {
      result = result && getDeviceAction()
          .equals(other.getDeviceAction());
    }
    result = result && getSpeechResultsList()
        .equals(other.getSpeechResultsList());
    result = result && (hasDialogStateOut() == other.hasDialogStateOut());
    if (hasDialogStateOut()) {
      result = result && getDialogStateOut()
          .equals(other.getDialogStateOut());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + eventType_;
    if (hasAudioOut()) {
      hash = (37 * hash) + AUDIO_OUT_FIELD_NUMBER;
      hash = (53 * hash) + getAudioOut().hashCode();
    }
    if (hasDeviceAction()) {
      hash = (37 * hash) + DEVICE_ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceAction().hashCode();
    }
    if (getSpeechResultsCount() > 0) {
      hash = (37 * hash) + SPEECH_RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getSpeechResultsList().hashCode();
    }
    if (hasDialogStateOut()) {
      hash = (37 * hash) + DIALOG_STATE_OUT_FIELD_NUMBER;
      hash = (53 * hash) + getDialogStateOut().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static AssistResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AssistResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AssistResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AssistResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AssistResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static AssistResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static AssistResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AssistResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static AssistResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static AssistResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static AssistResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static AssistResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(AssistResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The top-level message received by the client. A series of one or more
   * `AssistResponse` messages are streamed back to the client.
   * </pre>
   *
   * Protobuf type {@code google.assistant.embedded.v1alpha2.AssistResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.assistant.embedded.v1alpha2.AssistResponse)
      AssistResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AssistantProto.internal_static_google_assistant_embedded_v1alpha2_AssistResponse_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AssistantProto.internal_static_google_assistant_embedded_v1alpha2_AssistResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AssistResponse.class, Builder.class);
    }

    // Construct using com.google.assistant.embedded.v1alpha2.AssistResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSpeechResultsFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      eventType_ = 0;

      if (audioOutBuilder_ == null) {
        audioOut_ = null;
      } else {
        audioOut_ = null;
        audioOutBuilder_ = null;
      }
      if (deviceActionBuilder_ == null) {
        deviceAction_ = null;
      } else {
        deviceAction_ = null;
        deviceActionBuilder_ = null;
      }
      if (speechResultsBuilder_ == null) {
        speechResults_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        speechResultsBuilder_.clear();
      }
      if (dialogStateOutBuilder_ == null) {
        dialogStateOut_ = null;
      } else {
        dialogStateOut_ = null;
        dialogStateOutBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return AssistantProto.internal_static_google_assistant_embedded_v1alpha2_AssistResponse_descriptor;
    }

    public AssistResponse getDefaultInstanceForType() {
      return AssistResponse.getDefaultInstance();
    }

    public AssistResponse build() {
      AssistResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public AssistResponse buildPartial() {
      AssistResponse result = new AssistResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.eventType_ = eventType_;
      if (audioOutBuilder_ == null) {
        result.audioOut_ = audioOut_;
      } else {
        result.audioOut_ = audioOutBuilder_.build();
      }
      if (deviceActionBuilder_ == null) {
        result.deviceAction_ = deviceAction_;
      } else {
        result.deviceAction_ = deviceActionBuilder_.build();
      }
      if (speechResultsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          speechResults_ = java.util.Collections.unmodifiableList(speechResults_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.speechResults_ = speechResults_;
      } else {
        result.speechResults_ = speechResultsBuilder_.build();
      }
      if (dialogStateOutBuilder_ == null) {
        result.dialogStateOut_ = dialogStateOut_;
      } else {
        result.dialogStateOut_ = dialogStateOutBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof AssistResponse) {
        return mergeFrom((AssistResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(AssistResponse other) {
      if (other == AssistResponse.getDefaultInstance()) return this;
      if (other.eventType_ != 0) {
        setEventTypeValue(other.getEventTypeValue());
      }
      if (other.hasAudioOut()) {
        mergeAudioOut(other.getAudioOut());
      }
      if (other.hasDeviceAction()) {
        mergeDeviceAction(other.getDeviceAction());
      }
      if (speechResultsBuilder_ == null) {
        if (!other.speechResults_.isEmpty()) {
          if (speechResults_.isEmpty()) {
            speechResults_ = other.speechResults_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureSpeechResultsIsMutable();
            speechResults_.addAll(other.speechResults_);
          }
          onChanged();
        }
      } else {
        if (!other.speechResults_.isEmpty()) {
          if (speechResultsBuilder_.isEmpty()) {
            speechResultsBuilder_.dispose();
            speechResultsBuilder_ = null;
            speechResults_ = other.speechResults_;
            bitField0_ = (bitField0_ & ~0x00000008);
            speechResultsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSpeechResultsFieldBuilder() : null;
          } else {
            speechResultsBuilder_.addAllMessages(other.speechResults_);
          }
        }
      }
      if (other.hasDialogStateOut()) {
        mergeDialogStateOut(other.getDialogStateOut());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      AssistResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (AssistResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int eventType_ = 0;
    /**
     * <pre>
     * *Output-only* Indicates the type of event.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.AssistResponse.EventType event_type = 1;</code>
     */
    public int getEventTypeValue() {
      return eventType_;
    }
    /**
     * <pre>
     * *Output-only* Indicates the type of event.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.AssistResponse.EventType event_type = 1;</code>
     */
    public Builder setEventTypeValue(int value) {
      eventType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * *Output-only* Indicates the type of event.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.AssistResponse.EventType event_type = 1;</code>
     */
    public EventType getEventType() {
      EventType result = EventType.valueOf(eventType_);
      return result == null ? EventType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * *Output-only* Indicates the type of event.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.AssistResponse.EventType event_type = 1;</code>
     */
    public Builder setEventType(EventType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      eventType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * *Output-only* Indicates the type of event.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.AssistResponse.EventType event_type = 1;</code>
     */
    public Builder clearEventType() {
      
      eventType_ = 0;
      onChanged();
      return this;
    }

    private AudioOut audioOut_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        AudioOut, AudioOut.Builder, AudioOutOrBuilder> audioOutBuilder_;
    /**
     * <pre>
     * *Output-only* The audio containing the Assistant's response to the query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.AudioOut audio_out = 3;</code>
     */
    public boolean hasAudioOut() {
      return audioOutBuilder_ != null || audioOut_ != null;
    }
    /**
     * <pre>
     * *Output-only* The audio containing the Assistant's response to the query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.AudioOut audio_out = 3;</code>
     */
    public AudioOut getAudioOut() {
      if (audioOutBuilder_ == null) {
        return audioOut_ == null ? AudioOut.getDefaultInstance() : audioOut_;
      } else {
        return audioOutBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * *Output-only* The audio containing the Assistant's response to the query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.AudioOut audio_out = 3;</code>
     */
    public Builder setAudioOut(AudioOut value) {
      if (audioOutBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        audioOut_ = value;
        onChanged();
      } else {
        audioOutBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * *Output-only* The audio containing the Assistant's response to the query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.AudioOut audio_out = 3;</code>
     */
    public Builder setAudioOut(
        AudioOut.Builder builderForValue) {
      if (audioOutBuilder_ == null) {
        audioOut_ = builderForValue.build();
        onChanged();
      } else {
        audioOutBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * *Output-only* The audio containing the Assistant's response to the query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.AudioOut audio_out = 3;</code>
     */
    public Builder mergeAudioOut(AudioOut value) {
      if (audioOutBuilder_ == null) {
        if (audioOut_ != null) {
          audioOut_ =
            AudioOut.newBuilder(audioOut_).mergeFrom(value).buildPartial();
        } else {
          audioOut_ = value;
        }
        onChanged();
      } else {
        audioOutBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * *Output-only* The audio containing the Assistant's response to the query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.AudioOut audio_out = 3;</code>
     */
    public Builder clearAudioOut() {
      if (audioOutBuilder_ == null) {
        audioOut_ = null;
        onChanged();
      } else {
        audioOut_ = null;
        audioOutBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * *Output-only* The audio containing the Assistant's response to the query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.AudioOut audio_out = 3;</code>
     */
    public AudioOut.Builder getAudioOutBuilder() {
      
      onChanged();
      return getAudioOutFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * *Output-only* The audio containing the Assistant's response to the query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.AudioOut audio_out = 3;</code>
     */
    public AudioOutOrBuilder getAudioOutOrBuilder() {
      if (audioOutBuilder_ != null) {
        return audioOutBuilder_.getMessageOrBuilder();
      } else {
        return audioOut_ == null ?
            AudioOut.getDefaultInstance() : audioOut_;
      }
    }
    /**
     * <pre>
     * *Output-only* The audio containing the Assistant's response to the query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.AudioOut audio_out = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        AudioOut, AudioOut.Builder, AudioOutOrBuilder>
        getAudioOutFieldBuilder() {
      if (audioOutBuilder_ == null) {
        audioOutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            AudioOut, AudioOut.Builder, AudioOutOrBuilder>(
                getAudioOut(),
                getParentForChildren(),
                isClean());
        audioOut_ = null;
      }
      return audioOutBuilder_;
    }

    private DeviceAction deviceAction_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        DeviceAction, DeviceAction.Builder, DeviceActionOrBuilder> deviceActionBuilder_;
    /**
     * <pre>
     * *Output-only* Contains the action triggered by the query with the
     * appropriate payloads and semantic parsing.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DeviceAction device_action = 6;</code>
     */
    public boolean hasDeviceAction() {
      return deviceActionBuilder_ != null || deviceAction_ != null;
    }
    /**
     * <pre>
     * *Output-only* Contains the action triggered by the query with the
     * appropriate payloads and semantic parsing.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DeviceAction device_action = 6;</code>
     */
    public DeviceAction getDeviceAction() {
      if (deviceActionBuilder_ == null) {
        return deviceAction_ == null ? DeviceAction.getDefaultInstance() : deviceAction_;
      } else {
        return deviceActionBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * *Output-only* Contains the action triggered by the query with the
     * appropriate payloads and semantic parsing.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DeviceAction device_action = 6;</code>
     */
    public Builder setDeviceAction(DeviceAction value) {
      if (deviceActionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        deviceAction_ = value;
        onChanged();
      } else {
        deviceActionBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * *Output-only* Contains the action triggered by the query with the
     * appropriate payloads and semantic parsing.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DeviceAction device_action = 6;</code>
     */
    public Builder setDeviceAction(
        DeviceAction.Builder builderForValue) {
      if (deviceActionBuilder_ == null) {
        deviceAction_ = builderForValue.build();
        onChanged();
      } else {
        deviceActionBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * *Output-only* Contains the action triggered by the query with the
     * appropriate payloads and semantic parsing.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DeviceAction device_action = 6;</code>
     */
    public Builder mergeDeviceAction(DeviceAction value) {
      if (deviceActionBuilder_ == null) {
        if (deviceAction_ != null) {
          deviceAction_ =
            DeviceAction.newBuilder(deviceAction_).mergeFrom(value).buildPartial();
        } else {
          deviceAction_ = value;
        }
        onChanged();
      } else {
        deviceActionBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * *Output-only* Contains the action triggered by the query with the
     * appropriate payloads and semantic parsing.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DeviceAction device_action = 6;</code>
     */
    public Builder clearDeviceAction() {
      if (deviceActionBuilder_ == null) {
        deviceAction_ = null;
        onChanged();
      } else {
        deviceAction_ = null;
        deviceActionBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * *Output-only* Contains the action triggered by the query with the
     * appropriate payloads and semantic parsing.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DeviceAction device_action = 6;</code>
     */
    public DeviceAction.Builder getDeviceActionBuilder() {
      
      onChanged();
      return getDeviceActionFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * *Output-only* Contains the action triggered by the query with the
     * appropriate payloads and semantic parsing.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DeviceAction device_action = 6;</code>
     */
    public DeviceActionOrBuilder getDeviceActionOrBuilder() {
      if (deviceActionBuilder_ != null) {
        return deviceActionBuilder_.getMessageOrBuilder();
      } else {
        return deviceAction_ == null ?
            DeviceAction.getDefaultInstance() : deviceAction_;
      }
    }
    /**
     * <pre>
     * *Output-only* Contains the action triggered by the query with the
     * appropriate payloads and semantic parsing.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DeviceAction device_action = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        DeviceAction, DeviceAction.Builder, DeviceActionOrBuilder>
        getDeviceActionFieldBuilder() {
      if (deviceActionBuilder_ == null) {
        deviceActionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            DeviceAction, DeviceAction.Builder, DeviceActionOrBuilder>(
                getDeviceAction(),
                getParentForChildren(),
                isClean());
        deviceAction_ = null;
      }
      return deviceActionBuilder_;
    }

    private java.util.List<SpeechRecognitionResult> speechResults_ =
      java.util.Collections.emptyList();
    private void ensureSpeechResultsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        speechResults_ = new java.util.ArrayList<SpeechRecognitionResult>(speechResults_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        SpeechRecognitionResult, SpeechRecognitionResult.Builder, SpeechRecognitionResultOrBuilder> speechResultsBuilder_;

    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public java.util.List<SpeechRecognitionResult> getSpeechResultsList() {
      if (speechResultsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(speechResults_);
      } else {
        return speechResultsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public int getSpeechResultsCount() {
      if (speechResultsBuilder_ == null) {
        return speechResults_.size();
      } else {
        return speechResultsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public SpeechRecognitionResult getSpeechResults(int index) {
      if (speechResultsBuilder_ == null) {
        return speechResults_.get(index);
      } else {
        return speechResultsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public Builder setSpeechResults(
        int index, SpeechRecognitionResult value) {
      if (speechResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpeechResultsIsMutable();
        speechResults_.set(index, value);
        onChanged();
      } else {
        speechResultsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public Builder setSpeechResults(
        int index, SpeechRecognitionResult.Builder builderForValue) {
      if (speechResultsBuilder_ == null) {
        ensureSpeechResultsIsMutable();
        speechResults_.set(index, builderForValue.build());
        onChanged();
      } else {
        speechResultsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public Builder addSpeechResults(SpeechRecognitionResult value) {
      if (speechResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpeechResultsIsMutable();
        speechResults_.add(value);
        onChanged();
      } else {
        speechResultsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public Builder addSpeechResults(
        int index, SpeechRecognitionResult value) {
      if (speechResultsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSpeechResultsIsMutable();
        speechResults_.add(index, value);
        onChanged();
      } else {
        speechResultsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public Builder addSpeechResults(
        SpeechRecognitionResult.Builder builderForValue) {
      if (speechResultsBuilder_ == null) {
        ensureSpeechResultsIsMutable();
        speechResults_.add(builderForValue.build());
        onChanged();
      } else {
        speechResultsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public Builder addSpeechResults(
        int index, SpeechRecognitionResult.Builder builderForValue) {
      if (speechResultsBuilder_ == null) {
        ensureSpeechResultsIsMutable();
        speechResults_.add(index, builderForValue.build());
        onChanged();
      } else {
        speechResultsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public Builder addAllSpeechResults(
        Iterable<? extends SpeechRecognitionResult> values) {
      if (speechResultsBuilder_ == null) {
        ensureSpeechResultsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, speechResults_);
        onChanged();
      } else {
        speechResultsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public Builder clearSpeechResults() {
      if (speechResultsBuilder_ == null) {
        speechResults_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        speechResultsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public Builder removeSpeechResults(int index) {
      if (speechResultsBuilder_ == null) {
        ensureSpeechResultsIsMutable();
        speechResults_.remove(index);
        onChanged();
      } else {
        speechResultsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public SpeechRecognitionResult.Builder getSpeechResultsBuilder(
        int index) {
      return getSpeechResultsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public SpeechRecognitionResultOrBuilder getSpeechResultsOrBuilder(
        int index) {
      if (speechResultsBuilder_ == null) {
        return speechResults_.get(index);  } else {
        return speechResultsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public java.util.List<? extends SpeechRecognitionResultOrBuilder>
         getSpeechResultsOrBuilderList() {
      if (speechResultsBuilder_ != null) {
        return speechResultsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(speechResults_);
      }
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public SpeechRecognitionResult.Builder addSpeechResultsBuilder() {
      return getSpeechResultsFieldBuilder().addBuilder(
          SpeechRecognitionResult.getDefaultInstance());
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public SpeechRecognitionResult.Builder addSpeechResultsBuilder(
        int index) {
      return getSpeechResultsFieldBuilder().addBuilder(
          index, SpeechRecognitionResult.getDefaultInstance());
    }
    /**
     * <pre>
     * *Output-only* This repeated list contains zero or more speech recognition
     * results that correspond to consecutive portions of the audio currently
     * being processed, starting with the portion corresponding to the earliest
     * audio (and most stable portion) to the portion corresponding to the most
     * recent audio. The strings can be concatenated to view the full
     * in-progress response. When the speech recognition completes, this list
     * will contain one item with `stability` of `1.0`.
     * </pre>
     *
     * <code>repeated .google.assistant.embedded.v1alpha2.SpeechRecognitionResult speech_results = 2;</code>
     */
    public java.util.List<SpeechRecognitionResult.Builder>
         getSpeechResultsBuilderList() {
      return getSpeechResultsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        SpeechRecognitionResult, SpeechRecognitionResult.Builder, SpeechRecognitionResultOrBuilder>
        getSpeechResultsFieldBuilder() {
      if (speechResultsBuilder_ == null) {
        speechResultsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            SpeechRecognitionResult, SpeechRecognitionResult.Builder, SpeechRecognitionResultOrBuilder>(
                speechResults_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        speechResults_ = null;
      }
      return speechResultsBuilder_;
    }

    private DialogStateOut dialogStateOut_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        DialogStateOut, DialogStateOut.Builder, DialogStateOutOrBuilder> dialogStateOutBuilder_;
    /**
     * <pre>
     * *Output-only* Contains output related to the user's query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DialogStateOut dialog_state_out = 5;</code>
     */
    public boolean hasDialogStateOut() {
      return dialogStateOutBuilder_ != null || dialogStateOut_ != null;
    }
    /**
     * <pre>
     * *Output-only* Contains output related to the user's query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DialogStateOut dialog_state_out = 5;</code>
     */
    public DialogStateOut getDialogStateOut() {
      if (dialogStateOutBuilder_ == null) {
        return dialogStateOut_ == null ? DialogStateOut.getDefaultInstance() : dialogStateOut_;
      } else {
        return dialogStateOutBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * *Output-only* Contains output related to the user's query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DialogStateOut dialog_state_out = 5;</code>
     */
    public Builder setDialogStateOut(DialogStateOut value) {
      if (dialogStateOutBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        dialogStateOut_ = value;
        onChanged();
      } else {
        dialogStateOutBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * *Output-only* Contains output related to the user's query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DialogStateOut dialog_state_out = 5;</code>
     */
    public Builder setDialogStateOut(
        DialogStateOut.Builder builderForValue) {
      if (dialogStateOutBuilder_ == null) {
        dialogStateOut_ = builderForValue.build();
        onChanged();
      } else {
        dialogStateOutBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * *Output-only* Contains output related to the user's query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DialogStateOut dialog_state_out = 5;</code>
     */
    public Builder mergeDialogStateOut(DialogStateOut value) {
      if (dialogStateOutBuilder_ == null) {
        if (dialogStateOut_ != null) {
          dialogStateOut_ =
            DialogStateOut.newBuilder(dialogStateOut_).mergeFrom(value).buildPartial();
        } else {
          dialogStateOut_ = value;
        }
        onChanged();
      } else {
        dialogStateOutBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * *Output-only* Contains output related to the user's query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DialogStateOut dialog_state_out = 5;</code>
     */
    public Builder clearDialogStateOut() {
      if (dialogStateOutBuilder_ == null) {
        dialogStateOut_ = null;
        onChanged();
      } else {
        dialogStateOut_ = null;
        dialogStateOutBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * *Output-only* Contains output related to the user's query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DialogStateOut dialog_state_out = 5;</code>
     */
    public DialogStateOut.Builder getDialogStateOutBuilder() {
      
      onChanged();
      return getDialogStateOutFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * *Output-only* Contains output related to the user's query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DialogStateOut dialog_state_out = 5;</code>
     */
    public DialogStateOutOrBuilder getDialogStateOutOrBuilder() {
      if (dialogStateOutBuilder_ != null) {
        return dialogStateOutBuilder_.getMessageOrBuilder();
      } else {
        return dialogStateOut_ == null ?
            DialogStateOut.getDefaultInstance() : dialogStateOut_;
      }
    }
    /**
     * <pre>
     * *Output-only* Contains output related to the user's query.
     * </pre>
     *
     * <code>.google.assistant.embedded.v1alpha2.DialogStateOut dialog_state_out = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        DialogStateOut, DialogStateOut.Builder, DialogStateOutOrBuilder>
        getDialogStateOutFieldBuilder() {
      if (dialogStateOutBuilder_ == null) {
        dialogStateOutBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            DialogStateOut, DialogStateOut.Builder, DialogStateOutOrBuilder>(
                getDialogStateOut(),
                getParentForChildren(),
                isClean());
        dialogStateOut_ = null;
      }
      return dialogStateOutBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.assistant.embedded.v1alpha2.AssistResponse)
  }

  // @@protoc_insertion_point(class_scope:google.assistant.embedded.v1alpha2.AssistResponse)
  private static final AssistResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new AssistResponse();
  }

  public static AssistResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AssistResponse>
      PARSER = new com.google.protobuf.AbstractParser<AssistResponse>() {
    public AssistResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AssistResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AssistResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<AssistResponse> getParserForType() {
    return PARSER;
  }

  public AssistResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

