// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/assistant/embedded/v1alpha2/embedded_assistant.proto

package com.google.assistant.embedded.v1alpha2;

/**
 * <pre>
 * The estimated transcription of a phrase the user has spoken. This could be
 * a single segment or the full guess of the user's spoken query.
 * </pre>
 *
 * Protobuf type {@code google.assistant.embedded.v1alpha2.SpeechRecognitionResult}
 */
public  final class SpeechRecognitionResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:google.assistant.embedded.v1alpha2.SpeechRecognitionResult)
    SpeechRecognitionResultOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SpeechRecognitionResult.newBuilder() to construct.
  private SpeechRecognitionResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SpeechRecognitionResult() {
    transcript_ = "";
    stability_ = 0F;
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SpeechRecognitionResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            String s = input.readStringRequireUtf8();

            transcript_ = s;
            break;
          }
          case 21: {

            stability_ = input.readFloat();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return AssistantProto.internal_static_google_assistant_embedded_v1alpha2_SpeechRecognitionResult_descriptor;
  }

  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return AssistantProto.internal_static_google_assistant_embedded_v1alpha2_SpeechRecognitionResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            SpeechRecognitionResult.class, Builder.class);
  }

  public static final int TRANSCRIPT_FIELD_NUMBER = 1;
  private volatile Object transcript_;
  /**
   * <pre>
   * *Output-only* Transcript text representing the words that the user spoke.
   * </pre>
   *
   * <code>string transcript = 1;</code>
   */
  public String getTranscript() {
    Object ref = transcript_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      transcript_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * *Output-only* Transcript text representing the words that the user spoke.
   * </pre>
   *
   * <code>string transcript = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTranscriptBytes() {
    Object ref = transcript_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      transcript_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STABILITY_FIELD_NUMBER = 2;
  private float stability_;
  /**
   * <pre>
   * *Output-only* An estimate of the likelihood that the Assistant will not
   * change its guess about this result. Values range from 0.0 (completely
   * unstable) to 1.0 (completely stable and final). The default of 0.0 is a
   * sentinel value indicating `stability` was not set.
   * </pre>
   *
   * <code>float stability = 2;</code>
   */
  public float getStability() {
    return stability_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTranscriptBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, transcript_);
    }
    if (stability_ != 0F) {
      output.writeFloat(2, stability_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTranscriptBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, transcript_);
    }
    if (stability_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, stability_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof SpeechRecognitionResult)) {
      return super.equals(obj);
    }
    SpeechRecognitionResult other = (SpeechRecognitionResult) obj;

    boolean result = true;
    result = result && getTranscript()
        .equals(other.getTranscript());
    result = result && (
        Float.floatToIntBits(getStability())
        == Float.floatToIntBits(
            other.getStability()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRANSCRIPT_FIELD_NUMBER;
    hash = (53 * hash) + getTranscript().hashCode();
    hash = (37 * hash) + STABILITY_FIELD_NUMBER;
    hash = (53 * hash) + Float.floatToIntBits(
        getStability());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static SpeechRecognitionResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpeechRecognitionResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpeechRecognitionResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpeechRecognitionResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpeechRecognitionResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static SpeechRecognitionResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static SpeechRecognitionResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SpeechRecognitionResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static SpeechRecognitionResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static SpeechRecognitionResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static SpeechRecognitionResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static SpeechRecognitionResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(SpeechRecognitionResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The estimated transcription of a phrase the user has spoken. This could be
   * a single segment or the full guess of the user's spoken query.
   * </pre>
   *
   * Protobuf type {@code google.assistant.embedded.v1alpha2.SpeechRecognitionResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:google.assistant.embedded.v1alpha2.SpeechRecognitionResult)
      SpeechRecognitionResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AssistantProto.internal_static_google_assistant_embedded_v1alpha2_SpeechRecognitionResult_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AssistantProto.internal_static_google_assistant_embedded_v1alpha2_SpeechRecognitionResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SpeechRecognitionResult.class, Builder.class);
    }

    // Construct using com.google.assistant.embedded.v1alpha2.SpeechRecognitionResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      transcript_ = "";

      stability_ = 0F;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return AssistantProto.internal_static_google_assistant_embedded_v1alpha2_SpeechRecognitionResult_descriptor;
    }

    public SpeechRecognitionResult getDefaultInstanceForType() {
      return SpeechRecognitionResult.getDefaultInstance();
    }

    public SpeechRecognitionResult build() {
      SpeechRecognitionResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public SpeechRecognitionResult buildPartial() {
      SpeechRecognitionResult result = new SpeechRecognitionResult(this);
      result.transcript_ = transcript_;
      result.stability_ = stability_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof SpeechRecognitionResult) {
        return mergeFrom((SpeechRecognitionResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(SpeechRecognitionResult other) {
      if (other == SpeechRecognitionResult.getDefaultInstance()) return this;
      if (!other.getTranscript().isEmpty()) {
        transcript_ = other.transcript_;
        onChanged();
      }
      if (other.getStability() != 0F) {
        setStability(other.getStability());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      SpeechRecognitionResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (SpeechRecognitionResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private Object transcript_ = "";
    /**
     * <pre>
     * *Output-only* Transcript text representing the words that the user spoke.
     * </pre>
     *
     * <code>string transcript = 1;</code>
     */
    public String getTranscript() {
      Object ref = transcript_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        transcript_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <pre>
     * *Output-only* Transcript text representing the words that the user spoke.
     * </pre>
     *
     * <code>string transcript = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTranscriptBytes() {
      Object ref = transcript_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        transcript_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * *Output-only* Transcript text representing the words that the user spoke.
     * </pre>
     *
     * <code>string transcript = 1;</code>
     */
    public Builder setTranscript(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transcript_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * *Output-only* Transcript text representing the words that the user spoke.
     * </pre>
     *
     * <code>string transcript = 1;</code>
     */
    public Builder clearTranscript() {
      
      transcript_ = getDefaultInstance().getTranscript();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * *Output-only* Transcript text representing the words that the user spoke.
     * </pre>
     *
     * <code>string transcript = 1;</code>
     */
    public Builder setTranscriptBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transcript_ = value;
      onChanged();
      return this;
    }

    private float stability_ ;
    /**
     * <pre>
     * *Output-only* An estimate of the likelihood that the Assistant will not
     * change its guess about this result. Values range from 0.0 (completely
     * unstable) to 1.0 (completely stable and final). The default of 0.0 is a
     * sentinel value indicating `stability` was not set.
     * </pre>
     *
     * <code>float stability = 2;</code>
     */
    public float getStability() {
      return stability_;
    }
    /**
     * <pre>
     * *Output-only* An estimate of the likelihood that the Assistant will not
     * change its guess about this result. Values range from 0.0 (completely
     * unstable) to 1.0 (completely stable and final). The default of 0.0 is a
     * sentinel value indicating `stability` was not set.
     * </pre>
     *
     * <code>float stability = 2;</code>
     */
    public Builder setStability(float value) {
      
      stability_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * *Output-only* An estimate of the likelihood that the Assistant will not
     * change its guess about this result. Values range from 0.0 (completely
     * unstable) to 1.0 (completely stable and final). The default of 0.0 is a
     * sentinel value indicating `stability` was not set.
     * </pre>
     *
     * <code>float stability = 2;</code>
     */
    public Builder clearStability() {
      
      stability_ = 0F;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:google.assistant.embedded.v1alpha2.SpeechRecognitionResult)
  }

  // @@protoc_insertion_point(class_scope:google.assistant.embedded.v1alpha2.SpeechRecognitionResult)
  private static final SpeechRecognitionResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new SpeechRecognitionResult();
  }

  public static SpeechRecognitionResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpeechRecognitionResult>
      PARSER = new com.google.protobuf.AbstractParser<SpeechRecognitionResult>() {
    public SpeechRecognitionResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SpeechRecognitionResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SpeechRecognitionResult> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<SpeechRecognitionResult> getParserForType() {
    return PARSER;
  }

  public SpeechRecognitionResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

